{{- if and .Values.temporal.enabled .Values.temporal.admintools.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vdp.temporal.admintools" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-admintools
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "vdp.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-admintools
{{- end }}
