{{- if and .Values.temporal.enabled .Values.temporal.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.temporal" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-ui
data:
  config.yml: |
    {{- toYaml .Values.temporal.ui.config | nindent 4  }}
{{- end -}}
