apiVersion: v2
name: vdp
description: Versatile Data Pipeline (VDP) empowers the modern data stack to process unstructured data.
type: application
version: 0.1.3-alpha #! auto-updated by the CI workflow
appVersion: 0.9.0-alpha #! auto-updated by the CI workflow
keywords:
  - unstructured data
  - pipeline
  - ETL/ELT
  - AI
  - Data
sources:
  - https://github.com/instill-ai/vdp
home: "https://www.instill.tech"
icon: https://storage.googleapis.com/public-europe-west2-c-artifacts/imgs/vdp-logo.png
maintainers:
  - name: Instill AI LTD
    url: https://github.com/instill-ai
dependencies:
  - name: etcd
    repository: https://charts.bitnami.com/bitnami
    version: 8.8.1
    condition: etcd.enabled
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 8.5.1
    condition: elasticsearch.enabled
