{{- if .Values.persistence.enabled }}
{{- $modelRepository := .Values.persistence.persistentVolumeClaim.modelRepository -}}
{{- if not $modelRepository.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-repository-data-volume
  annotations:
  {{- range $key, $value := $modelRepository.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
spec:
  accessModes:
    - {{ $modelRepository.accessMode }}
  resources:
    requests:
      storage: {{ $modelRepository.size }}
  {{- if $modelRepository.storageClass }}
    {{- if eq "-" $modelRepository.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $modelRepository.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $condaPack := .Values.persistence.persistentVolumeClaim.condaPack -}}
{{- if not $condaPack.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: conda-pack-data-volume
  annotations:
  {{- range $key, $value := $condaPack.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
spec:
  accessModes:
    - {{ $condaPack.accessMode }}
  resources:
    requests:
      storage: {{ $condaPack.size }}
  {{- if $condaPack.storageClass }}
    {{- if eq "-" $condaPack.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $condaPack.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $database := .Values.persistence.persistentVolumeClaim.database -}}
{{- if not $database.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-data-volume
  annotations:
  {{- range $key, $value := $database.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ $database.accessMode }}
  resources:
    requests:
      storage: {{ $database.size }}
  {{- if $database.storageClass }}
    {{- if eq "-" $database.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $database.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $redis := .Values.persistence.persistentVolumeClaim.redis -}}
{{- if not $redis.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-volume
  annotations:
  {{- range $key, $value := $redis.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - {{ $redis.accessMode }}
  resources:
    requests:
      storage: {{ $redis.size }}
  {{- if $redis.storageClass }}
    {{- if eq "-" $redis.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $redis.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
